import { Scene } from "phaser";
export declare class Game extends Scene {
  private ship;
  private asteroids;
  private bullets;
  private particles;
  private missileExplosionParticles;
  private weaponManager;
  private score;
  private lives;
  private wave;
  private scoreText;
  private livesContainer;
  private livesSprites;
  private infinityText;
  private waveText;
  private weaponNameText;
  private weaponIcon;
  private cooldownCircle;
  private reloadText;
  private canShoot;
  private cooldownStartTime;
  private cooldownDuration;
  private cheatMode;
  constructor();
  create(): void;
  private createHUD;
  private updateLivesDisplay;
  private updateWeaponHUD;
  private showWeaponUnlock;
  private createStarField;
  private updateHUD;
  private toggleCheatMode;
  private shoot;
  private handleLaserHit;
  private missileHitAsteroid;
  private handleMissileAutoDetonate;
  private spawnWave;
  private bulletHitAsteroid;
  private shipHitAsteroid;
  private explodeAllMissiles;
  private nextWave;
  private createMissileExplosion;
  update(): void;
  private updateCooldownCircle;
}
