import { SoundPatch } from "./types";

const outputNode = {
  id: "output",
  type: "output" as const,
  label: "Output",
  position: { x: 740, y: 180 },
};

export const BATTLE_TANKS_AUDIO_PATCHES: SoundPatch[] = [
  {
    schemaVersion: 1,
    id: "battle-tanks-player-rumble",
    name: "Battle Tanks Player Rumble",
    category: "Rumble",
    duration: 0,
    preview: { intensity: 0.75, distance: 0, pan: 0 },
    nodes: [
      {
        id: "engine",
        type: "oscillator",
        label: "Engine Oscillator",
        position: { x: 80, y: 160 },
        waveform: "sawtooth",
        frequency: 22,
        detune: 0,
      },
      {
        id: "modulator",
        type: "lfo",
        label: "Rumble LFO",
        position: { x: 80, y: 330 },
        waveform: "sine",
        frequency: 5,
        depth: 2.5,
        target: "engine",
        targetParam: "frequency",
      },
      {
        id: "engine-gain",
        type: "gainEnvelope",
        label: "Throttle Gain",
        position: { x: 360, y: 170 },
        gain: 0.13,
        attack: 0.08,
        decay: 0.1,
        sustain: 1,
        release: 0.1,
      },
      outputNode,
    ],
    connections: [
      { from: "engine", to: "engine-gain" },
      { from: "engine-gain", to: "output" },
    ],
  },
  {
    schemaVersion: 1,
    id: "battle-tanks-enemy-rumble",
    name: "Battle Tanks Enemy Rumble",
    category: "Rumble",
    duration: 0,
    preview: { intensity: 0.8, distance: 320, pan: -0.45 },
    nodes: [
      {
        id: "enemy-engine",
        type: "oscillator",
        label: "Enemy Engine",
        position: { x: 70, y: 130 },
        waveform: "sawtooth",
        frequency: 18,
      },
      {
        id: "enemy-lfo",
        type: "lfo",
        label: "Track Wobble",
        position: { x: 70, y: 300 },
        waveform: "sine",
        frequency: 4.8,
        depth: 2.2,
        target: "enemy-engine",
        targetParam: "frequency",
      },
      {
        id: "attenuation",
        type: "spatialAttenuation",
        label: "Distance Gain",
        position: { x: 330, y: 130 },
        maxDistance: 1300,
        minGain: 0,
        maxGain: 0.09,
      },
      {
        id: "pan",
        type: "stereoPanner",
        label: "Directional Pan",
        position: { x: 540, y: 130 },
        pan: 0,
      },
      outputNode,
    ],
    connections: [
      { from: "enemy-engine", to: "attenuation" },
      { from: "attenuation", to: "pan" },
      { from: "pan", to: "output" },
    ],
  },
  {
    schemaVersion: 1,
    id: "battle-tanks-cannon-bang",
    name: "Battle Tanks Harsh Cannon Bang",
    category: "Weapon",
    duration: 0.28,
    preview: { intensity: 1, distance: 0, pan: 0 },
    nodes: [
      {
        id: "thump",
        type: "oscillator",
        label: "Low Bang",
        position: { x: 70, y: 90 },
        waveform: "square",
        frequency: 64,
        duration: 0.17,
      },
      {
        id: "thump-envelope",
        type: "gainEnvelope",
        label: "Bang Envelope",
        position: { x: 310, y: 90 },
        gain: 0.45,
        attack: 0.004,
        decay: 0.05,
        sustain: 0.25,
        release: 0.11,
        duration: 0.17,
      },
      {
        id: "crack",
        type: "noiseBurst",
        label: "Muzzle Crack",
        position: { x: 70, y: 280 },
        gain: 0.75,
        duration: 0.09,
        filterFrequency: 2400,
      },
      {
        id: "body",
        type: "noiseBurst",
        label: "Barrel Body",
        position: { x: 310, y: 280 },
        gain: 0.4,
        duration: 0.19,
        filterFrequency: 700,
        startTime: 0.015,
      },
      {
        id: "pan",
        type: "stereoPanner",
        label: "Shot Pan",
        position: { x: 550, y: 170 },
        pan: 0,
      },
      outputNode,
    ],
    connections: [
      { from: "thump", to: "thump-envelope" },
      { from: "thump-envelope", to: "pan" },
      { from: "crack", to: "pan" },
      { from: "body", to: "pan" },
      { from: "pan", to: "output" },
    ],
  },
  {
    schemaVersion: 1,
    id: "battle-tanks-impact-crunch",
    name: "Battle Tanks Armor Hit",
    category: "Impact",
    duration: 0.32,
    preview: { intensity: 0.9, distance: 180, pan: 0.25 },
    nodes: [
      {
        id: "metal",
        type: "oscillator",
        label: "Metal Bite",
        position: { x: 80, y: 120 },
        waveform: "triangle",
        frequency: 150,
        duration: 0.16,
      },
      {
        id: "crunch-envelope",
        type: "gainEnvelope",
        label: "Crunch Envelope",
        position: { x: 320, y: 120 },
        gain: 0.18,
        attack: 0.012,
        decay: 0.04,
        sustain: 0.35,
        release: 0.1,
        duration: 0.16,
      },
      {
        id: "sparks",
        type: "noiseBurst",
        label: "Sparks",
        position: { x: 80, y: 300 },
        gain: 0.14,
        duration: 0.16,
        filterFrequency: 1600,
      },
      {
        id: "pan",
        type: "stereoPanner",
        label: "Impact Pan",
        position: { x: 550, y: 180 },
        pan: 0,
      },
      outputNode,
    ],
    connections: [
      { from: "metal", to: "crunch-envelope" },
      { from: "crunch-envelope", to: "pan" },
      { from: "sparks", to: "pan" },
      { from: "pan", to: "output" },
    ],
  },
  {
    schemaVersion: 1,
    id: "battle-tanks-explosion",
    name: "Battle Tanks Explosion",
    category: "Explosion",
    duration: 0.82,
    preview: { intensity: 1, distance: 120, pan: -0.15 },
    nodes: [
      {
        id: "blast",
        type: "noiseBurst",
        label: "Blast Cloud",
        position: { x: 70, y: 90 },
        gain: 0.82,
        duration: 0.72,
        filterFrequency: 520,
      },
      {
        id: "shatter",
        type: "noiseBurst",
        label: "Shatter",
        position: { x: 70, y: 270 },
        gain: 0.38,
        duration: 0.2,
        filterFrequency: 1800,
      },
      {
        id: "low-hit",
        type: "oscillator",
        label: "Low Hit",
        position: { x: 310, y: 150 },
        waveform: "triangle",
        frequency: 58,
        duration: 0.62,
      },
      {
        id: "boom-envelope",
        type: "gainEnvelope",
        label: "Boom Envelope",
        position: { x: 510, y: 150 },
        gain: 0.25,
        attack: 0.012,
        decay: 0.16,
        sustain: 0.55,
        release: 0.35,
        duration: 0.62,
      },
      {
        id: "pan",
        type: "stereoPanner",
        label: "Explosion Pan",
        position: { x: 680, y: 190 },
        pan: 0,
      },
      outputNode,
    ],
    connections: [
      { from: "blast", to: "pan" },
      { from: "shatter", to: "pan" },
      { from: "low-hit", to: "boom-envelope" },
      { from: "boom-envelope", to: "pan" },
      { from: "pan", to: "output" },
    ],
  },
  {
    schemaVersion: 1,
    id: "battle-tanks-digital-taps",
    name: "Battle Tanks Digital Taps",
    category: "Music Cue",
    duration: 5.2,
    preview: { intensity: 1, distance: 0, pan: 0 },
    nodes: [
      ...[
        [392, 0, 0.26],
        [392, 0.34, 0.26],
        [523.25, 0.68, 0.52],
        [392, 1.32, 0.26],
        [523.25, 1.66, 0.26],
        [659.25, 2, 0.82],
        [523.25, 2.98, 0.5],
        [659.25, 3.58, 0.5],
        [783.99, 4.18, 0.9],
      ].flatMap(([frequency, startTime, duration], index) => [
        {
          id: `note-${index}`,
          type: "oscillator" as const,
          label: `Note ${index + 1}`,
          position: { x: 80, y: 70 + index * 42 },
          waveform: "square" as const,
          frequency,
          startTime,
          duration,
        },
        {
          id: `note-${index}-gain`,
          type: "gainEnvelope" as const,
          label: `Note ${index + 1} Gain`,
          position: { x: 340, y: 70 + index * 42 },
          gain: 0.1,
          attack: 0.025,
          decay: 0.12,
          sustain: 0.65,
          release: 0.16,
          startTime,
          duration,
        },
      ]),
      outputNode,
    ],
    connections: [
      ...Array.from({ length: 9 }, (_value, index) => ({
        from: `note-${index}`,
        to: `note-${index}-gain`,
      })),
      ...Array.from({ length: 9 }, (_value, index) => ({
        from: `note-${index}-gain`,
        to: "output",
      })),
    ],
  },
];

export const BATTLE_TANKS_AUDIO_PATCH_BY_ID = Object.fromEntries(
  BATTLE_TANKS_AUDIO_PATCHES.map((patch) => [patch.id, patch]),
) as Record<string, SoundPatch>;
