import { SoundPatch } from "./types";

const outputNode = {
  id: "output",
  type: "output" as const,
  label: "Output",
  position: { x: 760, y: 180 },
};

export const MARS_LANDER_AUDIO_PATCHES: SoundPatch[] = [
  {
    schemaVersion: 1,
    id: "mars-lander-thrust-loop",
    name: "Mars Lander Thrust Loop",
    category: "Rumble",
    duration: 0,
    preview: { intensity: 0.75, distance: 0, pan: 0 },
    nodes: [
      {
        id: "thrust-tone",
        type: "oscillator",
        label: "Thruster Tone",
        position: { x: 80, y: 130 },
        waveform: "sawtooth",
        frequency: 92,
        detune: -8,
      },
      {
        id: "fuel-flutter",
        type: "lfo",
        label: "Fuel Flutter",
        position: { x: 80, y: 290 },
        waveform: "triangle",
        frequency: 8.5,
        depth: 9,
        target: "thrust-tone",
        targetParam: "frequency",
      },
      {
        id: "thrust-filter",
        type: "filter",
        label: "Nozzle Filter",
        position: { x: 310, y: 130 },
        filterType: "lowpass",
        frequency: 740,
        q: 1.2,
      },
      {
        id: "thrust-gain",
        type: "gainEnvelope",
        label: "Throttle Gain",
        position: { x: 520, y: 130 },
        gain: 0.15,
        attack: 0.08,
        decay: 0.1,
        sustain: 1,
        release: 0.12,
      },
      {
        id: "thrust-pan",
        type: "stereoPanner",
        label: "Screen Pan",
        position: { x: 660, y: 130 },
        pan: 0,
      },
      outputNode,
    ],
    connections: [
      { from: "thrust-tone", to: "thrust-filter" },
      { from: "thrust-filter", to: "thrust-gain" },
      { from: "thrust-gain", to: "thrust-pan" },
      { from: "thrust-pan", to: "output" },
    ],
  },
  {
    schemaVersion: 1,
    id: "mars-lander-gear-deploy",
    name: "Mars Lander Gear Deploy",
    category: "Impact",
    duration: 0.38,
    preview: { intensity: 0.9, distance: 0, pan: 0 },
    nodes: [
      {
        id: "servo",
        type: "oscillator",
        label: "Servo Drop",
        position: { x: 80, y: 110 },
        waveform: "square",
        frequency: 210,
        duration: 0.24,
      },
      {
        id: "servo-envelope",
        type: "gainEnvelope",
        label: "Servo Envelope",
        position: { x: 320, y: 110 },
        gain: 0.16,
        attack: 0.006,
        decay: 0.08,
        sustain: 0.45,
        release: 0.13,
        duration: 0.24,
      },
      {
        id: "latch",
        type: "noiseBurst",
        label: "Latch Click",
        position: { x: 80, y: 280 },
        gain: 0.1,
        duration: 0.08,
        filterFrequency: 1800,
        startTime: 0.22,
      },
      outputNode,
    ],
    connections: [
      { from: "servo", to: "servo-envelope" },
      { from: "servo-envelope", to: "output" },
      { from: "latch", to: "output" },
    ],
  },
  {
    schemaVersion: 1,
    id: "mars-lander-touchdown",
    name: "Mars Lander Touchdown",
    category: "Impact",
    duration: 0.45,
    preview: { intensity: 1, distance: 0, pan: 0 },
    nodes: [
      {
        id: "pad-thump",
        type: "oscillator",
        label: "Pad Thump",
        position: { x: 80, y: 120 },
        waveform: "triangle",
        frequency: 72,
        duration: 0.32,
      },
      {
        id: "thump-envelope",
        type: "gainEnvelope",
        label: "Thump Envelope",
        position: { x: 310, y: 120 },
        gain: 0.2,
        attack: 0.01,
        decay: 0.09,
        sustain: 0.4,
        release: 0.18,
        duration: 0.32,
      },
      {
        id: "dust",
        type: "noiseBurst",
        label: "Martian Dust",
        position: { x: 80, y: 290 },
        gain: 0.12,
        duration: 0.24,
        filterFrequency: 900,
      },
      outputNode,
    ],
    connections: [
      { from: "pad-thump", to: "thump-envelope" },
      { from: "thump-envelope", to: "output" },
      { from: "dust", to: "output" },
    ],
  },
  {
    schemaVersion: 1,
    id: "mars-lander-level-cleared",
    name: "Mars Lander Level Cleared",
    category: "Music Cue",
    duration: 1.12,
    preview: { intensity: 1, distance: 0, pan: 0 },
    nodes: [
      ...[
        [392, 0, 0.18],
        [523.25, 0.2, 0.18],
        [659.25, 0.4, 0.22],
        [783.99, 0.66, 0.32],
      ].flatMap(([frequency, startTime, duration], index) => [
        {
          id: `clear-note-${index}`,
          type: "oscillator" as const,
          label: `Clear Note ${index + 1}`,
          position: { x: 80, y: 70 + index * 56 },
          waveform: "square" as const,
          frequency,
          startTime,
          duration,
        },
        {
          id: `clear-env-${index}`,
          type: "gainEnvelope" as const,
          label: `Clear Envelope ${index + 1}`,
          position: { x: 330, y: 70 + index * 56 },
          gain: 0.09,
          attack: 0.008,
          decay: 0.04,
          sustain: 0.5,
          release: 0.08,
          startTime,
          duration,
        },
      ]),
      outputNode,
    ],
    connections: [
      ...[0, 1, 2, 3].flatMap((index) => [
        { from: `clear-note-${index}`, to: `clear-env-${index}` },
        { from: `clear-env-${index}`, to: "output" },
      ]),
    ],
  },
  {
    schemaVersion: 1,
    id: "mars-lander-crash-explosion",
    name: "Mars Lander Crash Explosion",
    category: "Explosion",
    duration: 0.9,
    preview: { intensity: 1.15, distance: 0, pan: 0 },
    nodes: [
      {
        id: "blast",
        type: "noiseBurst",
        label: "Hull Blast",
        position: { x: 80, y: 110 },
        gain: 0.72,
        duration: 0.72,
        filterFrequency: 620,
      },
      {
        id: "low-bloom",
        type: "oscillator",
        label: "Low Bloom",
        position: { x: 80, y: 280 },
        waveform: "triangle",
        frequency: 48,
        duration: 0.7,
      },
      {
        id: "boom-envelope",
        type: "gainEnvelope",
        label: "Boom Envelope",
        position: { x: 320, y: 280 },
        gain: 0.24,
        attack: 0.01,
        decay: 0.2,
        sustain: 0.48,
        release: 0.36,
        duration: 0.7,
      },
      {
        id: "sparks",
        type: "noiseBurst",
        label: "Vector Sparks",
        position: { x: 330, y: 110 },
        gain: 0.24,
        duration: 0.22,
        filterFrequency: 2300,
      },
      outputNode,
    ],
    connections: [
      { from: "blast", to: "output" },
      { from: "sparks", to: "output" },
      { from: "low-bloom", to: "boom-envelope" },
      { from: "boom-envelope", to: "output" },
    ],
  },
  {
    schemaVersion: 1,
    id: "mars-lander-game-over",
    name: "Mars Lander Game Over",
    category: "Music Cue",
    duration: 1.35,
    preview: { intensity: 1, distance: 0, pan: 0 },
    nodes: [
      ...[
        [220, 0, 0.24],
        [174.61, 0.28, 0.24],
        [130.81, 0.58, 0.46],
      ].flatMap(([frequency, startTime, duration], index) => [
        {
          id: `game-over-note-${index}`,
          type: "oscillator" as const,
          label: `Game Over Note ${index + 1}`,
          position: { x: 80, y: 90 + index * 62 },
          waveform: "square" as const,
          frequency,
          startTime,
          duration,
        },
        {
          id: `game-over-env-${index}`,
          type: "gainEnvelope" as const,
          label: `Game Over Envelope ${index + 1}`,
          position: { x: 340, y: 90 + index * 62 },
          gain: 0.08,
          attack: 0.012,
          decay: 0.06,
          sustain: 0.55,
          release: 0.16,
          startTime,
          duration,
        },
      ]),
      outputNode,
    ],
    connections: [
      ...[0, 1, 2].flatMap((index) => [
        { from: `game-over-note-${index}`, to: `game-over-env-${index}` },
        { from: `game-over-env-${index}`, to: "output" },
      ]),
    ],
  },
  {
    schemaVersion: 1,
    id: "mars-lander-start",
    name: "Mars Lander Start",
    category: "Music Cue",
    duration: 0.5,
    preview: { intensity: 1, distance: 0, pan: 0 },
    nodes: [
      {
        id: "start-tone",
        type: "oscillator",
        label: "Launch Confirm",
        position: { x: 90, y: 140 },
        waveform: "square",
        frequency: 523.25,
        duration: 0.32,
      },
      {
        id: "start-envelope",
        type: "gainEnvelope",
        label: "Confirm Envelope",
        position: { x: 330, y: 140 },
        gain: 0.11,
        attack: 0.006,
        decay: 0.05,
        sustain: 0.55,
        release: 0.12,
        duration: 0.32,
      },
      outputNode,
    ],
    connections: [
      { from: "start-tone", to: "start-envelope" },
      { from: "start-envelope", to: "output" },
    ],
  },
  {
    schemaVersion: 1,
    id: "mars-lander-pause",
    name: "Mars Lander Pause",
    category: "Music Cue",
    duration: 0.28,
    preview: { intensity: 0.8, distance: 0, pan: 0 },
    nodes: [
      {
        id: "pause-tone",
        type: "oscillator",
        label: "Pause Tone",
        position: { x: 90, y: 140 },
        waveform: "triangle",
        frequency: 330,
        duration: 0.16,
      },
      {
        id: "pause-envelope",
        type: "gainEnvelope",
        label: "Pause Envelope",
        position: { x: 330, y: 140 },
        gain: 0.07,
        attack: 0.004,
        decay: 0.04,
        sustain: 0.4,
        release: 0.08,
        duration: 0.16,
      },
      outputNode,
    ],
    connections: [
      { from: "pause-tone", to: "pause-envelope" },
      { from: "pause-envelope", to: "output" },
    ],
  },
  {
    schemaVersion: 1,
    id: "mars-lander-resume",
    name: "Mars Lander Resume",
    category: "Music Cue",
    duration: 0.28,
    preview: { intensity: 0.8, distance: 0, pan: 0 },
    nodes: [
      {
        id: "resume-tone",
        type: "oscillator",
        label: "Resume Tone",
        position: { x: 90, y: 140 },
        waveform: "triangle",
        frequency: 494,
        duration: 0.16,
      },
      {
        id: "resume-envelope",
        type: "gainEnvelope",
        label: "Resume Envelope",
        position: { x: 330, y: 140 },
        gain: 0.07,
        attack: 0.004,
        decay: 0.04,
        sustain: 0.4,
        release: 0.08,
        duration: 0.16,
      },
      outputNode,
    ],
    connections: [
      { from: "resume-tone", to: "resume-envelope" },
      { from: "resume-envelope", to: "output" },
    ],
  },
  {
    schemaVersion: 1,
    id: "mars-lander-low-fuel",
    name: "Mars Lander Low Fuel",
    category: "Music Cue",
    duration: 0.62,
    preview: { intensity: 1, distance: 0, pan: 0 },
    nodes: [
      ...[
        [740, 0, 0.09],
        [740, 0.22, 0.09],
      ].flatMap(([frequency, startTime, duration], index) => [
        {
          id: `low-fuel-beep-${index}`,
          type: "oscillator" as const,
          label: `Low Fuel Beep ${index + 1}`,
          position: { x: 90, y: 110 + index * 70 },
          waveform: "square" as const,
          frequency,
          startTime,
          duration,
        },
        {
          id: `low-fuel-env-${index}`,
          type: "gainEnvelope" as const,
          label: `Low Fuel Envelope ${index + 1}`,
          position: { x: 340, y: 110 + index * 70 },
          gain: 0.08,
          attack: 0.003,
          decay: 0.02,
          sustain: 0.35,
          release: 0.04,
          startTime,
          duration,
        },
      ]),
      outputNode,
    ],
    connections: [
      ...[0, 1].flatMap((index) => [
        { from: `low-fuel-beep-${index}`, to: `low-fuel-env-${index}` },
        { from: `low-fuel-env-${index}`, to: "output" },
      ]),
    ],
  },
  {
    schemaVersion: 1,
    id: "mars-lander-title-placeholder",
    name: "Mars Lander Title Placeholder",
    category: "Music Cue",
    duration: 2.4,
    preview: { intensity: 0.65, distance: 0, pan: 0 },
    nodes: [
      ...[
        [196, 0, 0.4],
        [246.94, 0.48, 0.4],
        [293.66, 0.96, 0.4],
        [392, 1.44, 0.64],
      ].flatMap(([frequency, startTime, duration], index) => [
        {
          id: `title-note-${index}`,
          type: "oscillator" as const,
          label: `Placeholder Note ${index + 1}`,
          position: { x: 80, y: 60 + index * 60 },
          waveform: "triangle" as const,
          frequency,
          startTime,
          duration,
        },
        {
          id: `title-env-${index}`,
          type: "gainEnvelope" as const,
          label: `Placeholder Envelope ${index + 1}`,
          position: { x: 340, y: 60 + index * 60 },
          gain: 0.045,
          attack: 0.025,
          decay: 0.08,
          sustain: 0.58,
          release: 0.18,
          startTime,
          duration,
        },
      ]),
      outputNode,
    ],
    connections: [
      ...[0, 1, 2, 3].flatMap((index) => [
        { from: `title-note-${index}`, to: `title-env-${index}` },
        { from: `title-env-${index}`, to: "output" },
      ]),
    ],
  },
];

export const MARS_LANDER_AUDIO_PATCH_BY_ID = Object.fromEntries(
  MARS_LANDER_AUDIO_PATCHES.map((patch) => [patch.id, patch]),
) as Record<string, SoundPatch>;
